name: nextbox
version: '0.2'
summary: Nitrokey NextBox Core Snap
description: |
  Nitrokey NextBox Core Snap handling global configurations and startup behavior

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: amd64

apps:
  udisksctl:
    command: bin/udisksctl.sh
    plugs: [client]
    # NOTE: This is depreciated with snapd 2.25 however it needs to stay to
    # guarantee that all clients are updated correctly.
  udisksd:
    daemon: simple
    command: libexec/udisks2/udisksd
    slots: [service]
    plugs:
        - hardware-observe
        - mount-observe
  #ciborium:
  #  daemon: simple
  #  command: bin/ciborium
  #  plugs:
  #      - client
  #      - network-bind
  daemon:
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.30/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.30.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30.0/"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: bin/ddclient --daemon 300 -foreground
    daemon: simple
    plugs:
      - network
  exec:
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.30/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.30.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30.0/"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: bin/ddclient
    plugs:
      - network

layout:
  /etc/ddclient/ddclient.conf:
    bind-file: $SNAP_DATA/etc/ddclient/ddclient.conf
  /var/cache/ddclient/ddclient.cache:
    bind-file: $SNAP_DATA/var/cache/ddclient/ddclient.cache


slots:
  service:
    interface: udisks2

plugs:
  client:
    interface: udisks2

parts:
  nextbox-bins:
    plugin: dump
    source: bin/
    organize: 
      ./*: bin/

  nextbox-config:
    plugin: dump
    source: conf/

  nextbox-daemon:
    plugin: python
    source: nextbox_daemon/
    python-version: python3
    requirements: 
      - requirements.txt

  ddclient:
    plugin: dump
    source: https://github.com/ddclient/ddclient.git
    source-tag: 'v3.9.1'
    stage-packages:
      - libdata-validate-ip-perl
      - libio-socket-inet6-perl
      - libio-socket-ssl-perl
      - libjson-pp-perl
      - libsys-hostname-long-perl
      - perl
      - perl-base
      - perl-modules
    organize:
      ddclient: bin/ddclient
    stage:
      - bin/ddclient
      - usr/bin
      - usr/lib
      - usr/share
      - etc/perl

  udisks2:
    plugin: autotools
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/udisks2
    source-type: git
    source-branch: udisks/2.6.4
    configflags:
      - --enable-fhs-media
    install-via: destdir
    build-packages:
      - pkg-config
      - xsltproc
      - gtk-doc-tools
      - intltool
      - libglib2.0-dev
      - udev
      - libgudev-1.0-dev
      - libpolkit-gobject-1-dev
      - libpolkit-agent-1-dev
      - libacl1-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - libatasmart-dev
      - libsystemd-dev
      - gnome-common
    stage-packages:
      - libacl1
      - libatasmart4
      - libglib2.0-0
      - libgudev-1.0-0
      - libpam-systemd
      - libpolkit-agent-1-0
      - libpolkit-gobject-1-0
      - parted
      - gnome-common
    filesets:
      licenses:
        - usr/share/doc/*/*copyright*
      binaries:
        - bin/udisksctl
        - libexec/udisks2/udisksd
    prime:
      - $binaries
      - $licenses
      - lib
      - -lib/pkgconfig
      - -lib/systemd
      - -lib/cgmanager
      - libexec
      - sbin
      - usr/lib/*/*.so*

  #ciborium:
  #  plugin: go
  #  go-importpath: launchpad.net/ciborium
  #  source: .
  #  build-packages:
  #    - bzr
  #  override-build: |
  #    export GOPATH=$PWD/../go
  #    for d in udisks2 cmd/ciborium ; do
  #      cd $GOPATH/src/launchpad.net/ciborium/$d
  #      go test -v
  #    done

  common:
    plugin: dump
    source: .
    prime:
      - bin/udisksctl.sh

