name: nextbox
version: '0.1'
summary: Nitrokey NextBox Core Snap
description: |
  Nitrokey NextBox Core Snap handling global configurations and startup behavior

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: arm64
#  - build-on: amd64

parts:
  nextbox-bins:
    plugin: dump
    source: bin/
    organize: 
      ./*: bin/

  nextbox-config:
    plugin: dump
    source: conf/

  nextbox-daemon:
    plugin: python
    source: nextbox-daemon/
    python-version: python3
    stage-packages:
      - flask
    organize:
      ./*: nextbox-daemon/



